config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: "posts#index"

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/pin", to: "sessions#pin"
  post "/pin", to: "sessions#pin"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, except: [:destroy]
end

app/models/post.rb
class Post < ActiveRecord::Base
  PER_PAGE = 3

  include Voteable
  include Sluggable

  default_scope { order("created_at DESC") }

  belongs_to :creator, class_name: "User", foreign_key: :user_id
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }

  validates :url, presence: true
  validates :description, presence: true, uniqueness: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.limit(Post::PER_PAGE).offset(params[:offset])
    @pages = (Post.all.size / Post::PER_PAGE.to_f).ceil
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      @errors = @post.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote for a post once."
        end
        redirect_back(fallback_location(root_path))
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def is_creator_or_admin?
    logged_in? && (current_user.admin? || @post.creator == current_user)
  end

  def require_creator
    access_denied unless logged_in? && (current_user.admin? || @post.creator == current_user)
  end
end

app/views/posts/_comment.html.erb
<div class="well span8">
  <em>"<%= comment.body %>"</em>
  <% if show_post %>
    on <%= link_to comment.post.title, comment.post %>
  <% end %>
  <br/>
  <span class="quiet">by</span> <%= link_to comment.user.username, user_path(comment.user) %>
  <small>at <%= display_datetime(comment.created_at.localtime) %></small>
</div>

app/views/posts/_form.html.erb
<%= render "shared/errors", errors: @post.errors %>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |category| %>
    <div class="category-checkboxes">
      <%= category.check_box %>
      <%= category.label %>
    </div>
  <% end %>
  <br/>
  <%= f.submit submit_title, class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<%= render "shared/vote", obj: post %>

<div class="post">
    <%= render post.categories %>
  <p class="post-id">Post #<%= post.id %></p>
  <p>Post name: <%= post.title %></p>
  <p>Post URL: <%= link_to post.title, format_url(post.url) %></p>
  <p>Post description: <%= post.description %></p>
  <p>
    <span class="quiet">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
    <small>at <%= display_datetime(post.created_at.localtime) %></small>
  </p>
  <%= link_to "#{post.comments.size} comments", post_path(post) %>
</div>

app/views/posts/edit.html.erb
<%= render "shared/content_title", title: "Edit Post" %>

<%= render "form", submit_title: "Update Post" %>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts" %>

<div class="posts">
  <% @posts.each do |post| %>
    <div class="post-container">
      <%= render "post", post: post %>
    </div>
  <% end %>
</div>

<div id="pagination">
  <% @pages.times do |n| %>
    <% if (params[:offset].nil? && n == 0) || params[:offset].to_s == (n * Post::PER_PAGE).to_s %>
      <%= "| Page #{n + 1}" %>
    <% else %>
      <%= link_to "| Page #{n + 1}", posts_path(offset: n * Post::PER_PAGE) %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "shared/content_title", title: "Create post" %>

<%= render "form", submit_title: "Create Post" %>

app/views/posts/show.html.erb
<p class="pull-right">
  <%= link_to "[edit this post]", edit_post_path(@post) %>
</p>

<%= render @post.categories %>

<%= render "shared/content_title", title: @post.title %>

<ul class="post-info">
  <li>Title: <%= @post.title %></li>
  <li>Description: <%= @post.description %></li>
  <li>URL: <%= @post.url %></li>
</ul>

<% if logged_in? %>
  <h5>Create comment</h5>
  <%= form_for [@post, @comment] do |f| %>
    <%= render "shared/errors", errors: @comment.errors %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit "Create comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<% if @post.comments.any? %>
  <h5>Comments:</h5>
  <ul>
    <% @post.comments.reverse.each do |comment| %>
      <%= render "shared/vote", obj: comment %>
      <%= render "posts/comment", comment: comment, show_post: false %>
    <% end %>
  </ul>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= pluralize(@post.total_votes, "vote") %>");
<% else %>
  alert("You can only vote on a post once.")
<% end %>