config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: "posts#index"

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/pin", to: "sessions#pin"
  post "/pin", to: "sessions#pin"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, except: [:destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  before_save :generate_slug

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def generate_slug
    self.slug = self.name.parameterize
  end

  def to_param
    self.slug
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show]
  before_action :require_admin, except: [:show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "New category added"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render "shared/errors", errors: @category.errors %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit submit_title, class: "btn btn-primary" %>
<% end %>

app/views/categories/new.html.erb
<%= render "shared/content_title", title: "Create Category" %>

<%= render "form", submit_title: "Create category" %>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render "shared/content_title", title: header %>

<% @category.posts.each do |post| %>
  <%= render "posts/post", post: post %>
<% end %>